# Generated by Django 4.2.1 on 2023-05-24 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_name', models.CharField(max_length=50)),
                ('market_type', models.CharField(max_length=20)),
                ('adres', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=10)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('stores_num', models.IntegerField()),
                ('items', models.CharField(max_length=100)),
                ('giftcard', models.CharField(max_length=100)),
                ('toilet', models.CharField(max_length=10)),
                ('parkinglot', models.CharField(max_length=10)),
            ],
        ),
    ]
