# Generated by Django 4.2.1 on 2023-05-25 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postnum', models.IntegerField()),
                ('userid', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('wdate', models.DateTimeField()),
                ('contents', models.TextField()),
                ('hit', models.IntegerField(default=0)),
            ],
        ),
    ]
